"""Add is_visible and display_order to projects

Revision ID: 004
Revises: 003
Create Date: 2026-01-08 20:35:42.103022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults to handle existing rows
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('display_order')
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
