"""Add archivedAt to contact_submissions

Revision ID: 005
Revises: 004
Create Date: 2026-01-12 22:47:38.194142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
