"""Add profilePhotoUrl to About model

Revision ID: 006
Revises: 005
Create Date: 2026-01-15 22:39:42.366221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_me', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_me', schema=None) as batch_op:
        batch_op.drop_column('profile_photo_url')

    # ### end Alembic commands ###
